// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYUzbVJHBJqhW4eap-Lbcz9r0d9MIb2q8',
    appId: '1:948411909916:web:76f56782a64cb742f91cd9',
    messagingSenderId: '948411909916',
    projectId: 'travelmate-c16c9',
    authDomain: 'travelmate-c16c9.firebaseapp.com',
    storageBucket: 'travelmate-c16c9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2Ei9II2foQyHYnHzR0kfyCEVA-bDLCgU',
    appId: '1:948411909916:android:7655bb37d8bf3badf91cd9',
    messagingSenderId: '948411909916',
    projectId: 'travelmate-c16c9',
    storageBucket: 'travelmate-c16c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTLKBsE64QBBgTjPNiE_X5D19NdNmgA4E',
    appId: '1:948411909916:ios:ac881731094dd5dff91cd9',
    messagingSenderId: '948411909916',
    projectId: 'travelmate-c16c9',
    storageBucket: 'travelmate-c16c9.firebasestorage.app',
    iosBundleId: 'com.example.travelmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTLKBsE64QBBgTjPNiE_X5D19NdNmgA4E',
    appId: '1:948411909916:ios:ac881731094dd5dff91cd9',
    messagingSenderId: '948411909916',
    projectId: 'travelmate-c16c9',
    storageBucket: 'travelmate-c16c9.firebasestorage.app',
    iosBundleId: 'com.example.travelmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYUzbVJHBJqhW4eap-Lbcz9r0d9MIb2q8',
    appId: '1:948411909916:web:521e6abdb236ea77f91cd9',
    messagingSenderId: '948411909916',
    projectId: 'travelmate-c16c9',
    authDomain: 'travelmate-c16c9.firebaseapp.com',
    storageBucket: 'travelmate-c16c9.firebasestorage.app',
  );
}
